### ISSUE TITLE
basics tutorial (step 2) not accurate 

### ISSUE THREAD

**Issue by utkarshsingh99** [iterative/katacoda-scenarios#11]
![Screenshot from 2020-06-19 18-06-47](https://user-images.githubusercontent.com/32031518/85133137-c0840d80-b257-11ea-9c48-71536ed932de.png)
I think the term `dvc init` is missing here.
Also, the tutorial doesn't create a new directory and tries enabling DVC in the root directory. While it's perfectly fine, I don't think it's a good practice to do that.
Maybe we should change that?
@shcheklein @efiop

**Comment by efiop** [comment]
Hi @utkarshsingh99 ! Do you mean `data` scenario? https://github.com/iterative/katacoda-scenarios/tree/master/basics/data ?

**Comment by utkarshsingh99** [comment]
Yep

**Comment by efiop** [comment]
@utkarshsingh99 But there is `dvc init` there: https://github.com/iterative/katacoda-scenarios/blob/master/basics/data/step2.md

**Comment by utkarshsingh99** [comment]
Woah, that's weird. Am I viewing an outdated tutorial here? 
![Screenshot from 2020-06-19 19-26-07](https://user-images.githubusercontent.com/32031518/85140419-da771d80-b262-11ea-8662-e2bdfa9d8cc5.png)
Interestingly, now when I went on the same page, I found the page data the same as `step2.md`

**Comment by utkarshsingh99** [comment]
Oops, that was a mistake. My bad.
I'm sorry.
Should I close this?
