### ISSUE TITLE
Separate Installation from Initialization

### ISSUE THREAD

**Issue by iesahin** [iterative/katacoda-scenarios#23]
Currently DVC installation is described in https://katacoda.com/dvc/courses/get-started/initialize as a step. 

We can discuss several ways to install to DVC (snap, apt, pip, conda, bash completion) in a separate scenario and skip this step implicitly in other scenarios.

**Comment by jorgeorpinel** [comment]
Good idea but may not need a whole scenario for installation. We could just use `pip install dvc` (most used one) in the Initialization one, and link to https://dvc.org/doc/install for more methods.

Not sure why we even had `snap` TBH.

**Comment by iesahin** [comment]
Agreed. Closing.
