### ISSUE TITLE
review Get Started to be aligned with docs

### ISSUE THREAD

**Issue by shcheklein** [iterative/katacoda-scenarios#3]

**Comment by dashohoxha** [comment]
Actually I think that the structure of the "Get Started" docs should be revised to match the structure of the "Get Started" interactive tutorials.

For example the number of the subsections on the docs (15) is too many. I think it should be reduced (there are only 8 scenarios on the Get Started course, which are better aligned to the basic features of DVC).

Another example is explaining the remotes when apparently there is no reason for using them (https://dvc.org/doc/get-started/configure). In the Get Started course remotes are explained in the Data Sharing scenario, together with `dvc push` and `dvc pull`, which in my opinion makes more sense.

**Comment by shcheklein** [comment]
> For example the number of the subsections on the docs (15) is too many.

Not saying that there has been done too much research around that, but there were some principles and feedback in mind behind the current get started structure. E.g. each section should focus on a single command. Each section should be one page at most. Etc. 

I would say they have gotten bigger (not number of sections, sections themselves). Mostly because there was a lack of the User Guide extended sections (remember Install)?

I think that Get Started should be reflected with Katacoda as a single scenario. It's not ideal, but it's way more in-line with what Get Started should actually be.

**Comment by shcheklein** [comment]
> Another example is explaining the remotes 

So, it's just matter of changing the order - Add first, Configure after? May be also some renaming - like Setup Storage or something? Does not sound like a bit change. We have to introduce remotes anyway as soon as possible. Without them DVC is not useful.

**Comment by dashohoxha** [comment]
> I think that Get Started should be reflected with Katacoda as a single scenario.

Here it is: https://katacoda.com/dvc/courses/tutorials/get-started
I tried first to build Get Started as a single scenario. But guess what? It took me longer than 60 min to go through it, and this is a problem because Katacoda virtual environment is automatically restarted after 60 min. So, I split it into smaller scenarios.

**Comment by shcheklein** [comment]
It looks like you are trying to put literally everything we have in expandable sections and even more. E.g. dos2unix and md5 explanations. With get started there is not intention to go deep - just show basics from the very high level (and provide links and/or expandable to go deep)
