### ISSUE TITLE
example versioning takes too long to complete end-to-end

### ISSUE THREAD

**Issue by shcheklein** [iterative/katacoda-scenarios#4]
Katacoda is pretty slow, it's easy to get the environment shut at the very last stage.

We can probably split the step 5 into a separate scenario and put a link to it. It should include steps 1 and 5 from this one - just to illustrate the `dvc run`.

we should also improve the messaging when we run train.py - put some message in the script that it's running

**Comment by shcheklein** [comment]
And we should do some changes and show the purpose of `dvc repro`.

**Comment by dashohoxha** [comment]
If somebody needs any help with getting familiar to coding Katacoda scenarios, I can help.
But I think that Katacoda docs are good enough, and even a student can build such scenarios (assuming that he knows the right steps of the tutorial).

**Comment by shcheklein** [comment]
> If somebody needs any help with getting familiar to coding Katacoda scenarios, I can help.
But I think that Katacoda docs are good enough, and even a student can build such scenarios (assuming that he knows the right steps of the tutorial).

not sure I got the comment. What does it have to do with issue?

**Comment by dashohoxha** [comment]
> not sure I got the comment. What does it have to do with issue?

Who is going to fix this issue? Does he know how to work with katacoda tutorials or maybe needs some help?

**Comment by shcheklein** [comment]
> Who is going to fix this issue? Does he know how to work with katacoda tutorials or maybe needs some help?

got it now 👍 :)
