### ISSUE TITLE
Tutorials/Versioning doesn't start

### ISSUE THREAD

**Issue by iesahin** [iterative/katacoda-scenarios#48]
The scenario at https://katacoda.com/iex/courses/tutorials/versioning doesn't pass this screen. 

![Screen Shot 2021-03-14 at 18 02 03](https://user-images.githubusercontent.com/476310/111073353-6dda3800-84ef-11eb-92ed-de964de1ffd9.png)

I waited about ~10 minutes but it doesn't start. Init scripts seem OK.

**Comment by shcheklein** [comment]
Is it still valid?

**Comment by iesahin** [comment]
Yes, it's still valid. I'm taking a look into this.

**Comment by iesahin** [comment]
The cause is actually a [single line in step4.md](https://github.com/iterative/katacoda-scenarios/blame/master/tutorials/versioning/step4.md#L9) that reads:

`<img url="/dvc/courses/tutorials/versioning/assets/versioning.png" />`

HTML tags are not allowed in Katacoda but I didn't suspect that it could stop the whole thing. There is not a single error message anywhere either. 

In order to find that, I did some bisection. (I won't commit these, just to show how I debugged. 😄 ) 

![Screen Shot 2021-04-25 at 21 30 00](https://user-images.githubusercontent.com/476310/116004992-d0a21180-a60d-11eb-9b6a-ee2795559297.png)

Will be fixing soon @shcheklein

**Comment by shcheklein** [comment]
@iesahin thanks! Katacoda - yay! :)
