### ISSUE TITLE
Update scenarios with the new Docker containers in `hub.docker.com/u/dvcorg` 

### ISSUE THREAD

**Issue by iesahin** [iterative/katacoda-scenarios#52]
Currently, the containers are run from `emresult/` namespace. We are discussing the new naming convention in iterative/dvc.org#2354 and after we decide on new names for the containers, we need to push the containers with the new names and update the scenarios to use these newer containers.

**Comment by shcheklein** [comment]
Is it done?

**Comment by iesahin** [comment]
This is done and automated.
