### ISSUE TITLE
remove tutorials/get-started ?

### ISSUE THREAD

**Issue by shcheklein** [iterative/katacoda-scenarios#6]
@dashohoxha  it looks like a duplicate right now. Is there a purpose of having it?

**Comment by dashohoxha** [comment]
It is a duplicate, but in a different format (as a whole big tutorial, instead of small tutorials).
No real purpose of having it. It is still there because it is quite easy to delete it and I didn't want to rush for deleting it.

**Comment by shcheklein** [comment]
let's delete it then - to simplify and keep less things to support/review
