### ISSUE TITLE
faulty link

### ISSUE THREAD

**Issue by kaiogu** [iterative/katacoda-scenarios#8]
The link to the wikipedia page for do graphs gets displayed incorrectly due to the ")" in the url and katacodas markdown engine interprets this as the end of the link.
The link ends up pointing to 
>https://en.wikipedia.org/wiki/DOT_(graph_description_language

Note the missing parens at the end. 

What gets displayed in katacoda is:
>With the option --dot it can output a DOT graph). However the package pydot should be installed first:

Note the extra parens after "DOT graph".

**Comment by iesahin** [comment]
This content seems to be removed already. Thanks.
